export const memeData = [
  {
    title: "Mem 1",
    upvotes: 0,
    downvotes: 0,
    img: "images/image1.jpg",
    starred: false,
  },
  {
    title: "Mem 2",
    upvotes: 1,
    downvotes: 2,
    img: "images/image2.jpeg",
    starred: false,
  },

  {
    title: "Mem 3",
    upvotes: 10,
    downvotes: 2,
    img: "images/image3.jpg",
    starred: false,
  },
  {
    title: "Mem 4",
    upvotes: 3,
    downvotes: 1,
    img: "images/image4.jpg",
    starred: false,
  },
  {
    title: "Mem 5",
    upvotes: 5,
    downvotes: 2,
    img: "images/image5.jpg",
    starred: false,
  },
  {
    title: "Mem 6",
    upvotes: 6,
    downvotes: 2,
    img: "images/image6.jpg",
    starred: false,
  },
  {
    title: "Mem 7",
    upvotes: 1,
    downvotes: 0,
    img: "images/image7.jpg",
    starred: false,
  },
  {
    title: "Mem 8",
    upvotes: 1,
    downvotes: 0,
    img: "images/image8.jpg",
    starred: false,
  },
  {
    title: "Mem 9",
    upvotes: 100,
    downvotes: 1,
    img: "images/image9.jpg",
    starred: true,
  },
  {
    title: "Mem 10",
    upvotes: 1,
    downvotes: 0,
    img: "images/image10.jpg",
    starred: false,
  },
  {
    title: "Mem 11",
    upvotes: 1,
    downvotes: 0,
    img: "images/image11.jpg",
    starred: false,
  },
  {
    title: "Mem 12",
    upvotes: 1,
    downvotes: 0,
    img: "images/image12.jpg",
    starred: false,
  },
  {
    title: "Mem 13",
    upvotes: 1,
    downvotes: 0,
    img: "images/image13.jpg",
    starred: false,
  },
  {
    title: "Mem 14",
    upvotes: 50,
    downvotes: 40,
    img: "images/image14.jpeg",
    starred: false,
  },
  {
    title: "Mem 15",
    upvotes: 1,
    downvotes: 0,
    img: "images/image15.jpg",
    starred: false,
  },
  {
    title: "Mem 16",
    upvotes: 1,
    downvotes: 0,
    img: "images/image16.jpg",
    starred: false,
  },
  {
    title: "Mem 17",
    upvotes: 1,
    downvotes: 0,
    img: "images/image17.jpg",
    starred: false,
  },
  {
    title: "Mem 18",
    upvotes: 1,
    downvotes: 0,
    img: "images/image18.webp",
    starred: false,
  },
  {
    title: "Mem 19",
    upvotes: 1,
    downvotes: 0,
    img: "images/image19.jpg",
    starred: false,
  },
  {
    title: "Mem 20",
    upvotes: 1,
    downvotes: 0,
    img: "images/image20.webp",
    starred: false,
  },
  {
    title: "Mem 21",
    upvotes: 1,
    downvotes: 0,
    img: "images/image21.webp",
    starred: false,
  },
  {
    title: "Mem 22",
    upvotes: 1,
    downvotes: 0,
    img: "images/image22.jpg",
    starred: false,
  },
  {
    title: "Mem 23",
    upvotes: 1,
    downvotes: 0,
    img: "images/image23.webp",
    starred: false,
  },
  {
    title: "Mem 24",
    upvotes: 1,
    downvotes: 0,
    img: "images/image24.webp",
    starred: false,
  },
  {
    title: "Mem 25",
    upvotes: 1,
    downvotes: 0,
    img: "images/image25.webp",
    starred: true,
  },
  {
    title: "Mem 26",
    upvotes: 1,
    downvotes: 0,
    img: "images/image26.jpg",
    starred: false,
  },
  {
    title: "Mem 27",
    upvotes: 33,
    downvotes: 0,
    img: "images/image27.jpg",
    starred: true,
  },
];
