export const memeData = [
  {
    id: "1",
    title: "Mem 1",
    upvotes: 0,
    downvotes: 0,
    img: "images/image1.jpg",
    starred: false,
  },
  {
    id: "2",
    title: "Mem 2",
    upvotes: 1,
    downvotes: 2,
    img: "images/image2.jpeg",
    starred: false,
  },

  {
    id: "3",
    title: "Mem 3",
    upvotes: 10,
    downvotes: 2,
    img: "images/image3.jpg",
    starred: false,
  },
  {
    id: "4",
    title: "Mem 4",
    upvotes: 3,
    downvotes: 1,
    img: "images/image4.jpg",
    starred: false,
  },
  {
    id: "5",
    title: "Mem 5",
    upvotes: 5,
    downvotes: 2,
    img: "images/image5.jpg",
    starred: false,
  },
  {
    id: "6",
    title: "Mem 6",
    upvotes: 6,
    downvotes: 2,
    img: "images/image6.jpg",
    starred: false,
  },
  {
    id: "7",
    title: "Mem 7",
    upvotes: 1,
    downvotes: 0,
    img: "images/image7.jpg",
    starred: false,
  },
  {
    id: "8",
    title: "Mem 8",
    upvotes: 1,
    downvotes: 0,
    img: "images/image8.jpg",
    starred: false,
  },
  {
    id: "9",
    title: "Mem 9",
    upvotes: 100,
    downvotes: 1,
    img: "images/image9.jpg",
    starred: true,
  },
  {
    id: "10",
    title: "Mem 10",
    upvotes: 1,
    downvotes: 0,
    img: "images/image10.jpg",
    starred: false,
  },
  {
    id: "11",
    title: "Mem 11",
    upvotes: 1,
    downvotes: 0,
    img: "images/image11.jpg",
    starred: false,
  },
  {
    id: "12",
    title: "Mem 12",
    upvotes: 1,
    downvotes: 0,
    img: "images/image12.jpg",
    starred: false,
  },
  {id: "13",
    title: "Mem 13",
    upvotes: 1,
    downvotes: 0,
    img: "images/image13.jpg",
    starred: false,
  },
  {
    id: "14",
    title: "Mem 14",
    upvotes: 50,
    downvotes: 40,
    img: "images/image14.jpeg",
    starred: false,
  },
  {
    id: "15",
    title: "Mem 15",
    upvotes: 1,
    downvotes: 0,
    img: "images/image15.jpg",
    starred: false,
  },
  {
    id: "16",
    title: "Mem 16",
    upvotes: 1,
    downvotes: 0,
    img: "images/image16.jpg",
    starred: false,
  },
  {
    id: "17",
    title: "Mem 17",
    upvotes: 1,
    downvotes: 0,
    img: "images/image17.jpg",
    starred: false,
  },
  {
    id: "18",
    title: "Mem 18",
    upvotes: 1,
    downvotes: 0,
    img: "images/image18.webp",
    starred: false,
  },
  {
    id: "19",
    title: "Mem 19",
    upvotes: 1,
    downvotes: 0,
    img: "images/image19.jpg",
    starred: false,
  },
  {
    id: "20",
    title: "Mem 20",
    upvotes: 1,
    downvotes: 0,
    img: "images/image20.webp",
    starred: false,
  },
  {
    id: "21",
    title: "Mem 21",
    upvotes: 1,
    downvotes: 0,
    img: "images/image21.webp",
    starred: false,
  },
  {
    id: "22",
    title: "Mem 22",
    upvotes: 1,
    downvotes: 0,
    img: "images/image22.jpg",
    starred: false,
  },
  {
    id: "23",
    title: "Mem 23",
    upvotes: 1,
    downvotes: 0,
    img: "images/image23.webp",
    starred: false,
  },
  {
    id: "24",
    title: "Mem 24",
    upvotes: 1,
    downvotes: 0,
    img: "images/image24.webp",
    starred: false,
  },
  {
    id: "25",
    title: "Mem 25",
    upvotes: 1,
    downvotes: 0,
    img: "images/image25.webp",
    starred: true,
  },
  {
    id: "26",
    title: "Mem 26",
    upvotes: 1,
    downvotes: 0,
    img: "images/image26.jpg",
    starred: false,
  },
  {
    id: "27",
    title: "Mem 27",
    upvotes: 33,
    downvotes: 0,
    img: "images/image27.jpg",
    starred: true,
  },
];
